tattle-made/feluda

CODE_OF_CONDUCT.md
CONTRIBUTING.md

just added to mostly boilerplate content for contributing and coc.

(chore) add contributing and CoC readmes

---

src/api/.gitignore
src/api/core/operators/vid_vec_rep_resnet.py
src/api/core/operators/vid_vec_rep_resnet_requirements.in
src/api/core/operators/vid_vec_rep_resnet_requirements.txt
src/api/requirements.in
src/api/requirements.txt

- Added pyinstrument for cpu profiling
- Added gitignore requirement for pyinstrument
- Disabled compress function for operator
- Removed ffmpy dependency as it is not required now

Add cpu profiling and optimize operator

---

src/api/Dockerfile.image_vec_rep_resnet
src/api/Dockerfile.vid_vec_rep_resnet
src/api/image_vec_operator_profile.py
src/api/image_vec_operator_profile_memray.sh
src/api/image_vec_operator_profile_pyinstrument.sh
src/api/video_vec_operator_profile.py
src/api/video_vec_operator_profile_memray.sh
src/api/video_vec_operator_profile_pyinstrument.sh

- Added image vec python script
- Added image memray benchmarking shell script
- Added image pyinstrument benchmarking shell script
- Added video vec python script
- Added video memray benchmarking shell script
- Added video pyinstrument benchmarking shell script
- Added chmod executable for all scripts in image and vid dockerfiles

Benchmark scripts

---

src/api/Dockerfile.image_vec_rep_resnet
src/api/Dockerfile.vid_vec_rep_resnet
src/api/core/operators/image_vec_rep_resnet_requirements.in
src/api/core/operators/image_vec_rep_resnet_requirements.txt
src/api/core/operators/vid_vec_rep_resnet_requirements.in
src/api/core/operators/vid_vec_rep_resnet_requirements.txt
src/api/image_vec_operator_profile_memray.sh
src/api/image_vec_operator_profile_pyinstrument.sh
src/api/requirements.txt
src/api/video_vec_operator_profile.py
src/api/video_vec_operator_profile_memray.sh
src/api/video_vec_operator_profile_pyinstrument.sh

- Updated shebang in shell scripts
- Updated operator dockerfiles
- Updated requirements

Fix modular operator issues

---

.github/workflows/docker-push-vidvec.yml
src/api/Dockerfile.vid_vec_rep_resnet
src/api/core/operators/vid_vec_rep_resnet_requirements.txt

- Added pytorch optimization for AWS graviton in dockerfile
- Modified requirements.txt to work with multi-arch support
- Modified docker vid vec github action with multi-arch build support

Optimize docker for multi-arch builds

---

.github/workflows/docker-push-vidvec.yml

Fix Unexpected input(s) 'platforms'

---

src/api/Dockerfile.vid_vec_rep_resnet

- Fixed AWS Graviton opt commands in dockerfile

Fix Graviton commands

---

src/api/Dockerfile.vid_vec_rep_resnet
src/api/core/operators/vid_vec_rep_resnet_requirements.txt

- Added conditional for building multi-arch cpu pytorch
- Revert base image for Graviton compatibility

Add pytorch arch conditional

---

.github/workflows/docker-push-vidvec.yml

- Modified tag naming syntax in github actions

Fix tag name issue

---

src/api/.gitignore
src/api/core/operators/vid_vec_rep_resnet.py
src/api/core/store/es_vec.py
src/api/requirements.in
src/api/requirements.txt
src/api/test_video_es_vec.py
src/api/video_vec_es_indexer.py
src/api/video_vec_es_search_benchmark_locust.py
src/api/video_vec_es_search_benchmark_locust.sh

- Added locust out files to gitignore
- Fixed import issues in video operator
- Fixed file size limit to 10mb in video operator
- Optimized video operator to run with constant memory usage
- Fixed UnboundLocalError in es_vec.py
- Updated flask_cors package for locust compatibility
- Added locust package to requirements.in
- Regenerated feluda core requirements.txt
- Added tests for indexing and searching videos in elastic search
- Added video operator ES search benchmark locust file
- Added python file to index videos as init for ES load testing
- Added bash script to perform video load testing

Add ElasticSearch benchmarking

---

docker-compose.yml
src/api/core/feluda.py
src/api/server.py

- Enabled rabbitmq disabled in PR https://github.com/tattle-made/feluda/pull/74/files
- Updated rabbitmq version

Enable RabbitMQ

---

.gitignore
src/api/Dockerfile.test_worker
src/api/core/queue/rabbit_mq.py
src/api/test_worker.py
src/api/tests/test_worker.py
src/api/tests/test_writer.py

- this PR writes a test to queue and index video files
- To run this PR - make sure the `Dockerfile` is changed to `Dockerfile.test_worker`
- Then do `docker-compose up` -> exec into the `feluda_api` and download the following python libraries
- `pip install PyYAML dacite numpy elasticsearch pika opencv-python-headless scipy `
- `pip install torch==2.2.0+cpu torchvision==0.17.0+cpu --find-links https://download.pytorch.org/whl/torch_stable.html`
- After that run the test files from the test folder -> `test_worker.py` and `test_writer.py`

test: worker to queue and index video files

---

src/core/models/media_factory.py
src/core/operators/audio_vec_embedding.py
src/core/operators/test_audio_vec_embedding.py
src/core/operators/test_image_vec_rep_resnet.py
src/core/operators/test_vid_vec_rep_resnet.py
src/tests/test_media_factory.py

- This PR resolves https://github.com/tattle-made/DAU_tipline/issues/61

fix: operator tests support Media Factory

---

src/core/operators/test_vid_vec_rep_resnet.py
src/core/operators/vid_vec_rep_resnet.py

This PR resolves https://github.com/tattle-made/DAU_tipline/issues/66

fix: context manager handles vidoes

---

src/worker/audiovec/Dockerfile.audio_worker
src/worker/audiovec/Dockerfile.audio_worker.graviton
src/worker/audiovec/audio_payload_writer.py
src/worker/audiovec/audio_worker.py
src/worker/audiovec/config.yml

This PR resolves https://github.com/tattle-made/DAU_tipline/issues/74

feat: worker for audio operator

---

src/benchmark/audiovec/Dockerfile.audio_vec_embedding
src/benchmark/audiovec/audio_vec_operator_cprofile.py
src/benchmark/audiovec/audio_vec_operator_cprofile.sh
src/benchmark/audiovec/audio_vec_operator_multicore.py
src/benchmark/audiovec/audio_vec_operator_multicore.sh
src/benchmark/audiovec/audio_vec_operator_profile.py
src/benchmark/audiovec/audio_vec_operator_profile_memray.sh
src/benchmark/audiovec/audio_vec_operator_profile_pyinstrument.sh
src/benchmark/audiovec/audio_vec_operator_time.py
src/benchmark/audiovec/audio_vec_operator_time.sh
src/benchmark/benchmark-audio.sh
src/core/operators/audio_vec_embedding_requirements.in
src/core/operators/audio_vec_embedding_requirements.txt

This PR resolves https://github.com/tattle-made/DAU_tipline/issues/75

test: benchmarking scripts for audiovec operator

---

src/benchmark/benchmark-video.sh
src/benchmark/vidvec/Dockerfile.vid_vec_rep_resnet
src/benchmark/vidvec/Dockerfile.vid_vec_rep_resnet.graviton
src/benchmark/vidvec/video_vec_operator_cprofile.py
src/benchmark/vidvec/video_vec_operator_multicore.py
src/benchmark/vidvec/video_vec_operator_profile.py
src/benchmark/vidvec/video_vec_operator_time.py

This PR resolves https://github.com/tattle-made/DAU_tipline/issues/76

fix: updating vidvec benchmark scripts

---

src/benchmark/audiovec/Dockerfile.audio_vec_embedding.graviton

This PR resolves https://github.com/tattle-made/DAU_tipline/issues/77

ci: audiovec benchmark graviton dockerfile

---

.github/workflows/merge-dev-hotfix.yml
.github/workflows/merge-main.yml

- Removed conditional on merge main workflow
- Removed environment label from merge dev hotfix workflow
- Modified docker secrets name

ci: Fix secrets access

---

docker-compose.yml
src/core/store/postgresql.py
src/worker/vidvec/video_worker.py

- Created trigger function for updating timestamp
- Modified create table function with conditional for table
- Added create table for storing CRC
- Added function to create trigger for table
- Modified store and update functions to store worker_column
- Added postgres init and call to storing video CRC
- Pinned images in docker compose

feat: Add video CRC to postgres

---

src/worker/audiovec/audio_worker.py
src/worker/vidvec/video_worker.py

- Modified video worker column value

feat: Added audio CRC write to postgres

---

.github/workflows/pr-security.yml
CHANGELOG.md

- Removed ignored vulnerabilities that were fixed
- Updated github action versions to latest

Update pr security workflow

---

.github/workflows/pr-tests.yml
pyproject.toml
tests/feluda_unit_tests/models/test_media_factory.py

resolves - https://github.com/tattle-made/feluda/issues/469

ci: run tests on PR

---

.github/workflows/operator-test.yml
.github/workflows/pr-security.yml
operators/cluster_embeddings/pyproject.toml
operators/dimension_reduction/pyproject.toml
operators/image_vec_rep_resnet/pyproject.toml
operators/vid_vec_rep_clip/pyproject.toml
pyproject.toml
scripts/validate_toml_files.py

this PR also fixes https://github.com/tattle-made/feluda/issues/526 along with updating packages.

package upgrade and script changes

---

examples/01_plot_tsne_videos.ipynb

Fixes issue #540   
I've also added code to capture the installation outputs. You can check the working examples over here -  
[Example 1](https://colab.research.google.com/github/omkar-334/feluda/blob/fix-colab-examples/examples/01_plot_tsne_videos.ipynb)  
[Example 2](https://colab.research.google.com/github/omkar-334/feluda/blob/fix-colab-examples/examples/02_plot_cluster_videos.ipynb)  
(The `open in colab` link is different since its on my branch so I'm attaching it here)

Fix colab examples

---

.github/dependabot.yml

Update root folder and schedule interval

---

operators/classify_video_zero_shot/classify_video_zero_shot.py
operators/classify_video_zero_shot/pyproject.toml
operators/classify_video_zero_shot/test.py

Move Classify_video_zero_shot operator

---

operators/classify_video_zero_shot/classify_video_zero_shot.py

fix: delete input file after processing (classify_video_zero_shot operator)

---

tests/feluda_integration_tests/test_07_feluda_and_vid_vec_rep_clip_and_dimension_reduction.py

solves: #563 
Created multi-operator(feluda, vid_vec_rep_clip and dimension_reduction) integration test.

Add Integration Test for feluda, feluda-vid-vec-rep-clip and feluda-dimension-reduction

---

pyproject.toml

Raised PR: Investigate best practices for pyproject.toml files [#547](https://github.com/tattle-made/feluda/issues/547)
- [Python Packaging Guide](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#writing-pyproject-toml)
- [Marimo](https://github.com/marimo-team/marimo)
- [FastAPI](https://github.com/tiangolo/fastapi)
Hey! 
1. Could you share some info about the authors and maintainers so I can replace the placeholders
2. Also does feluda have a CLI that we can add under [project.scripts]

#547 Update pyproject.toml with Best Practices

---

operators/cluster_embeddings/README.md
operators/cluster_embeddings/__init__.py
operators/cluster_embeddings/cluster_embeddings.py
operators/cluster_embeddings/test.py

tests passing on py3.12, win11  
operator working

refactor: `cluster_embeddings` operator

---

operators/video_hash_tmk/test.py
operators/video_hash_tmk/video_hash_tmk.py

fixed the hash extraction logic for the tmk operator using instructions mentioned in the official repo - https://github.com/facebook/ThreatExchange/tree/main/tmk

fix: video has tmk logic
